//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing_log
    {
        public long billing_id { get; set; }
        public long user_id { get; set; }
        public bool trade_type { get; set; }
        public string participant_user_id { get; set; }
        public decimal money { get; set; }
        public string remark { get; set; }
        public bool is_delete { get; set; }
        public string trade_user { get; set; }
        public string participant_user_name { get; set; }
        public System.DateTime trade_time { get; set; }
        public long team_id { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
