//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class billing_systemEntities : DbContext
    {
        public billing_systemEntities()
            : base("name=billing_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<billing_log> billing_log { get; set; }
        public DbSet<sys_notice> sys_notice { get; set; }
        public DbSet<sys_user> sys_user { get; set; }
        public DbSet<team> team { get; set; }
        public DbSet<team_user> team_user { get; set; }
        public DbSet<vyw_billing_log_team> vyw_billing_log_team { get; set; }
        public DbSet<vyw_notice_user> vyw_notice_user { get; set; }
        public DbSet<vyw_team_user> vyw_team_user { get; set; }
    }
}
