//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        public long user_id { get; set; }
        public string user_name { get; set; }
        public string user_nickname { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public Nullable<int> user_role { get; set; }
        public string user_face { get; set; }
        public Nullable<int> apply_status { get; set; }
        public string email_token { get; set; }
        public Nullable<System.DateTime> email_token_time { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public int login_count { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
    }
}
