//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vyw_team_user
    {
        public string teamName { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public long teamUserID { get; set; }
        public Nullable<long> parentID { get; set; }
        public int status { get; set; }
        public string user_name { get; set; }
        public string user_nickname { get; set; }
        public string user_email { get; set; }
        public Nullable<int> user_role { get; set; }
        public string user_face { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public int login_count { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public long userID { get; set; }
        public long teamID { get; set; }
        public string parentName { get; set; }
        public string parentNickName { get; set; }
        public Nullable<int> apply_status { get; set; }
    }
}
